{
 "title": "Speedtest",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Average Download Mbps",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"speedtest-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> drop(columns: [\"server_id\", \"server_name\", \"server_country_name\"])\n  |> filter(fn:(r) =>\n    r._measurement == \"speedtest\" and\n    r._field == \"download_speed_mbps\"\n  )\n  |> mean()"
    }
   ]
  },
  {
   "title": "Average Upload Mbps",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"speedtest-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> drop(columns: [\"server_id\", \"server_name\", \"server_country_name\"])\n  |> filter(fn:(r) =>\n    r._measurement == \"speedtest\" and\n    r._field == \"upload_speed_mbps\"\n  )\n  |> mean()"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"speedtest-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> drop(columns: [\"server_id\", \"server_name\", \"server_country_name\"])\n  |> filter(fn:(r) =>\n    r._measurement == \"speedtest\" and\n    r._field == \"ping\"\n  )\n  |> mean()"
    }
   ]
  },
  {
   "title": "Speed History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> drop(columns: [\"server_id\", \"server_name\", \"server_country_name\"])\n|> filter(fn: (r) =>\n    r._measurement == \"speedtest\" and\n    (r._field == \"download_speed_mbps\" or r._field == \"upload_speed_mbps\")\n  )\n|> map(fn: (r) => ({\n        r with\n        _field: \n          if r._field == \"download_speed_mbps\" then \"Download Speed Mbps\"\n          else if r._field == \"upload_speed_mbps\" then \"Upload Speed Mbps\"\n          else r._field\n      })\n    )\n|> sort(columns:[\"_time\"], desc: false)"
    }
   ]
  },
  {
   "title": "Latency History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"speedtest-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> drop(columns: [\"server_id\", \"server_name\", \"server_country_name\"])\n|> filter(fn: (r) =>\n    r._measurement == \"speedtest\" and\n    r._field == \"ping\"\n  )\n|> map(fn: (r) => ({\n        r with\n        _field: \n          if r._field == \"ping\" then \"Ping ms\"\n          else r._field\n      })\n    )\n|> sort(columns:[\"_time\"], desc: false)\n  "
    }
   ]
  },
  {
   "title": "Records",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"speedtest-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> sort(columns:[\"_time\"], desc: true)"
    }
   ]
  }
 ]
}